## -- Example - 7 :: File download (CSV/Excel) from generated data -- ##
## Purpose: Create data and provide a download link.
import streamlit as st
import pandas as pd
import numpy as np

st.title("Download Example")
df = pd.DataFrame(np.random.randn(100, 4), columns=list("ABCD"))
st.dataframe(df.head())
csv = df.to_csv(index=False).encode('utf-8')
st.download_button("Download CSV", data=csv, file_name="random.csv", mime="text/csv")


## Explanation: st.download_button offers client-side download of generated bytes.
## Result: Click to download CSV file.